### ISSUE TITLE
Show more button not responding

### ISSUE THREAD

**Issue by digitalcourtney87** [localgovdrupal/localgov_news#12]
Clicking the show more button on the [news listing page](https://dev.londoncouncils.gov.uk/news) doesn't surface older news articles.

**Comment by danchamp** [comment]
I'm seeing expected behaviour on that page @digitalcourtney87 - the listing will not include the 3 featured articles (as per BHCC), so at the moment there are only 5 to show.

This will be covered by #6 - we shouldn't show that link unless there's more news to show.
