### ISSUE TITLE
Remove newsroom image thumbnails from navigation flow

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_news#20]
Newroom tab order is currently sub-optimal, with both news article titles and thumbnails linking to the article page.

Assuming that having a clickable thumbnail is a good idea, proposed solution is to set a tabindex of -1 on thumbnails.

**Comment by markconroy** [comment]
A very simple thing we could do here is not link the image, then use CSS like this:

.node--teaser {
  position: relative;
}

.teaser__title a::after {
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
  top: 0;
  content: "";
  display: block;
}

Then the whole teaser will be clickable. You can see more details: 
https://adrianroselli.com/2020/02/block-links-cards-clickable-regions-etc.html

**Comment by danchamp** [comment]
Fixed in #31
