### ISSUE TITLE
Theme refactor: localgov news

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_news#25]
# Sample newsroom: http://localgov.dev.mark.ie/news
# Sample news article: http://localgov.dev.mark.ie/news/2021/test-news-post-number-2-really-important-one

- [ ] Put the templates in place in the theme
- [ ] Move styling into localgov_base theme
- [ ] confirm feature parity

**Comment by finnlewis** [comment]
@markconroy could you elaborate on progress here ?

**Comment by markconroy** [comment]
No update on this just yet Finn. I was leaving this to later in the work load as it's not part of the official distribution yet. 

I think the work for this should be minimal when we look at it as most of it will be taken care of from the teaser view mode and other stuff I am working on.

**Comment by willguv** [comment]
@danchamp and @markconroy to review, and push news to a 1.x release

**Comment by markconroy** [comment]
I'm closing this in favour of an issue open in the localgov_base repo

https://github.com/localgovdrupal/localgov_base/issues/80
