### ISSUE TITLE
Creating a Newsroom Node first before news articles causes WSOD

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_news#30]
From clean install, enabling localgov_news:core and localgov_newsroom.
1. Create a newsroom node with title (no featured news as nothing to feature yet)
2. Save
3. WSOD
The following is the error:
````
The website encountered an unexpected error. Please try again later.
Error: Call to a member function get() on null in Drupal\localgov_newsroom\Plugin\Block\FeaturedNewsBlock->getFeaturedNews() (line 68 of modules/contrib/localgov_news/modules/localgov_newsroom/src/Plugin/Block/FeaturedNewsBlock.php).
````

**Comment by andybroomfield** [comment]
So this seems to happen if it's not published. I've enabled localgov_workflow so its using the publishing states (not sure if this also effects vanilla publishing using status).

**Comment by ekes** [comment]
Equally enabling a block before there is a newsroom creates a WSOD.

I think there are a few assumptions in the code about there being results.

**Comment by keelanfh** [comment]
Looks to be fixed.
