### ISSUE TITLE
Reduce 'featured news' complexity: Alternative to 'promote to front page'

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_news#32]
Follow-up to #31 

At the moment the complexity of the featured news on a newsroom is mixing the 'entity reference' featured content and the 'promoted to front page' featured content.

 * Add a pseudo field 'checkbox' to the news article content type form: 'Add to newsroom featured' as an 'extra field' 
 * Councils can enable/disable the field, and hence functionality, by having the field on the form or not
 * When the field is checked on save (post save), load the newsroom, push the item to the top of the featured items entity reference field (and should there be a max, dropped the last one off).

The views can then be changed to only include / exclude the items in the reference list.

**Comment by keelanfh** [comment]
Looks like this was completed in the PRs referenced above.
