### ISSUE TITLE
Extend test coverage

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_news#4]
Tests are in place only for the news article content type and a news article page.

Coverage needs to be extended to cover all blocks and the newsroom sub-module.

**Comment by andybroomfield** [comment]
We need tests for :
- Setting up a news content type, and verifying it shows in the list
- Adding featured news content type and showing it is in the featured block and not the list
- Adding an image to the default news images, selecting it from the list, and verifing that gets used as the news thumbnail
- Javascript test for the show more loads more news articles
