### ISSUE TITLE
Search results: set consistent view mode [localgov_news]

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_news#70]
As part of reviewing the search functionality, it has become apparent that there is no consistent presentation of search results across the distribution.

We need to

- [ ]  ensure each content type has a search_result display node
- [ ]  configure the search_result display mode to have the appropriate fields

In the case of localgov_news, we need to ensure appropriate configuration for

- [ ]  localgov_newsroom
- [ ]  localgov_news_article

**Comment by andybroomfield** [comment]
There is an issue here in that the search result is currently used for the news search and has a particular display, so maybe we do the same as localgov_directories and create a seperate view mode for the news search.

/cc @finnlewis @danchamp
