### ISSUE TITLE
Drupal 10 support

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_news#77]
Issue to track any changes needed to support Drupal 10

**Comment by stephen-cox** [comment]
[Invalid permissions will trigger runtime exceptions in Drupal 10.](https://www.drupal.org/node/3193348) Permissions should be defined in a permissions.yml file or a permission callback.

Permissions of user role: "News editor":
- delete own media
- update any image media
- view all localgov_news_article revisions
- view any unpublished localgov_news_article content
- view own media
- view own unpublished localgov_news_article content

**Comment by andybroomfield** [comment]
It looks like there are some missing dependencies at play.
Localgov News should at least also enable `drupal:media` or maybe even `localgov_core:localgov_media` and is also missing the module [view unpublished](https://www.drupal.org/project/view_unpublished) for those view own unpublished permissions.

**Comment by stephen-cox** [comment]
Closing as we have D10 support working
